# Generated by Django 5.1.3 on 2024-11-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-id']},
        ),
    ]
